spring:
  application:
    name: auth-ms
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update # Use 'update' em ambientes de desenvolvimento; 'validate' ou 'none' em ambientes de produção
      show-sql: true # Mostra SQL executado no console

server:
  port: 8081

=======
    url: jdbc:postgresql://postgresql:5432/auth-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081
>>>>>>> refs/remotes/origin/main
api:
  security:
    token:
      secret: my-secret-key