version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWOR:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: eccomerce
      MYSQL_USER: angelo
      MYSQL_PASSWORD: 101010ab
    ports:
      - "3306:3306"
