version: '3.9'

services:
#  rabbitmq:
#    image: "rabbitmq:3.8.6-management"
#    container_name: rabbitmq-broker
#    ports:
#      - 5672:5672
#      - 15672:15672
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  auth-ms:
    container_name: auth-ms
    build:
      context: .
      dockerfile: ./auth-ms/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresql

    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
